version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-10-15T19-57-03Z
    command: server --console-address ":9001" /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio124
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: opticbox_db
    environment:
      POSTGRES_DB: opticbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  minio_data:
  pgdata:
