# Generated by Django 5.2 on 2025-05-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opticbox', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lens',
            name='user',
        ),
    ]
