# Generated by Django 5.2 on 2025-05-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opticbox', '0002_authuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
