# Generated by Django 5.2 on 2025-05-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticbox', '0003_remove_lens_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен?'),
        ),
    ]
