# Generated by Django 5.2 on 2025-04-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestservice',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='requestservice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='requestservice',
            name='quantity',
        ),
        migrations.AddField(
            model_name='request',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='request',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО получателя'),
        ),
    ]
